```{r}
library(plotly)
library(dplyr)

# Loading data Iris
data(iris)
head(iris)
```


```{r}
# A function to calculate regression and correlation lines
regression_lines <- function(data, species) {
  data_sp <- data %>% filter(Species == species)
  model <- lm(Petal.Length ~ Sepal.Length, data = data_sp)
  
  # We generate a range for the regression line
  x_range <- seq(min(data_sp$Sepal.Length), max(data_sp$Sepal.Length), length.out = 100)
  y_range <- predict(model, newdata = data.frame(Sepal.Length = x_range))
  
  # We calculate the correlation
  cor_value <- round(cor(data_sp$Sepal.Length, data_sp$Petal.Length), 2)
  
  data.frame(Sepal.Length = x_range, Petal.Length = y_range, Species = species, Correlation = cor_value)
}
```


```{r}
# We generate regression lines and correlation
lines_setosa <- regression_lines(iris, "setosa")
lines_versicolor <- regression_lines(iris, "versicolor")
lines_virginica <- regression_lines(iris, "virginica")

# Basic dot plot with filter
fig <- plot_ly(
  data = iris,
  x = ~Sepal.Length,
  y = ~Petal.Length,
  color = ~Species,
  colors = c('blue', 'orange', 'green'),
  type = 'scatter',
  mode = 'markers',
  transforms = list(
    list(
      type = 'filter',
      target = ~Species,
      operation = '=',
      value = "setosa"
    )
  )
)
```


```{r}
# We add regression lines
fig <- fig %>%
  add_lines(
    data = lines_setosa,
    x = ~Sepal.Length,
    y = ~Petal.Length,
    line = list(color = 'blue', width = 1),
    name = paste("Setosa (r =", lines_setosa$Correlation[1], ")")
  ) %>%
  add_lines(
    data = lines_versicolor,
    x = ~Sepal.Length,
    y = ~Petal.Length,
    line = list(color = 'orange', width = 1),
    name = paste("Versicolor (r =", lines_versicolor$Correlation[1], ")")
  ) %>%
  add_lines(
    data = lines_virginica,
    x = ~Sepal.Length,
    y = ~Petal.Length,
    line = list(color = 'green', width = 1),
    name = paste("Virginica (r =", lines_virginica$Correlation[1], ")")
  )
```


```{r}
# We add a menu for filtering
fig <- fig %>%
  layout(
    title = "Dynamic Lines with Correlation Coefficients",
    xaxis = list(title = "Sepal Length (cm)"),
    yaxis = list(title = "Petal Length (cm)"),
    updatemenus = list(
      list(
        buttons = list(
          list(
            method = "restyle",
            args = list("transforms[0].value", "setosa"),
            label = "Iris-setosa"
          ),
          list(
            method = "restyle",
            args = list("transforms[0].value", "versicolor"),
            label = "Iris-versicolor"
          ),
          list(
            method = "restyle",
            args = list("transforms[0].value", "virginica"),
            label = "Iris-virginica"
          ),
          list(
            method = "restyle",
            args = list("transforms[0].value", unique(iris$Species)),
            label = "All"
          )
        ),
        direction = "down",
        x = 0.1,
        y = 1.15,
        showactive = TRUE
      )
    )
  )

fig
```

